"""Publish readable methods with inventory-derived coverage and metadata tables."""
import json
from pathlib import Path
from html import escape

def build_methods(out):
 out=Path(out);inventory=json.loads((out/'source_inventory.json').read_text());model=json.loads((out/'model_diagnostics.json').read_text());phase=json.loads((out/'sensitivity_diagnostics.json').read_text())['phase_conditioned_counts'];coverage=json.loads((out/'coverage.json').read_text());enc=json.loads((out/'encounter_metadata.json').read_text());meta=json.loads((out/'sweap_metadata.json').read_text())
 counts=enc['counts'];n=coverage['waveform_records']
 encsection=f'''<section id="encounters"><h2>PSP encounter tags</h2><p>This dataset spans {coverage['date_start']} to {coverage['date_end']} and is associated with <strong>Encounter 23 (E23)</strong>, whose perihelion was on 22 March 2025. <a href="{escape(enc['source'],quote=True)}">NASA’s mission update</a> identifies the encounter observing interval as 18–27 March.</p><p>Tags distinguish <strong>{counts.get('within',0):,} bursts on encounter dates</strong>, <strong>{counts.get('before',0):,} before</strong>, and <strong>{counts.get('after',0):,} after</strong>. The latter two carry “E23 context” labels.</p><p>This is a date-based association, not a CDF operating-mode flag. Membership uses the UTC calendar date of the burst start, including 18 and 27 March. The announcement does not supply exact UTC boundary times. The rule is restricted to reviewed 4–31 March coverage; other dates remain unassigned pending review. Use the Encounter period filter or search for E23. Catalog columns retain encounter number, period, tag, perihelion date and source.</p></section>'''
 tab=''.join(f'<tr><td>{d}</td><td>{k:,}</td></tr>' for d,k in coverage['daily_counts'].items())
 covsection=f'''<section id="coverage"><h2>Data coverage and missing channels</h2><p>{coverage['files']} CDF files contain {coverage['source_records']:,} source records; {n:,} waveform records appear in the atlas. Every nominal E23 date (18–27 March) has a file. Dates without files within this collection’s wider span: {', '.join(coverage['missing_calendar_dates_in_span']) or 'none'}. Daily file coverage does not establish that every selected or downlinked TDS burst is present.</p><p>Electron-count data are absent in {len(coverage['digital_missing_events'])} records (events {', '.join(map(str,coverage['digital_missing_events']))}). They are displayed as absent and excluded from the scan-reference training and all count-based fits. Internal count-preview arrays use zero placeholders only to preserve array shape; those are not measurements. Use <code>counts_present</code> or <code>Burst_Time_Series_SWEAP_Exists_Flag</code> when reading catalogs. {len(coverage['incomplete_analog_events'])} records have incomplete analog configurations; {len(coverage['no_analog_events'])} of these has no analog waveform but retains its digital channel. Primary and alternate analog fits and SCM-pair analysis require complete analog configurations.</p><details><summary>Daily record counts</summary><table><thead><tr><th>UTC date</th><th>Bursts</th></tr></thead><tbody>{tab}</tbody></table></details><p><a href="coverage.json">Coverage inventory</a></p></section>'''
 rows=''.join(f"<tr><td><code>{v['hex']}</code></td><td>{v['decimal']}</td><td>{v['n']:,}</td></tr>" for v in meta['values']['SWEAP_Status'])
 masks=''.join('<p><code>'+name+'</code>: '+', '.join(f"<code>{v['hex']}</code> ({v['n']:,} records)" for v in meta['values'][name])+'.</p>' for name in ['SWEAP_Electron_Mask','SWEAP_Ion_Mask'])
 low,high=meta['sweep_start_range_present_digital_s']
 sweap=f'''<section id="sweap-mode"><h2>What the CDF tells us about SPAN-e operation</h2><p>All {meta['files']} CDFs were inspected. <code>SWEAP_Status</code> is a coded status word, and the electron/ion masks describe coded anode selection. Their attributes do not define the bits or map them to named SPAN-e modes. <code>SWEAP_Start</code> is seconds since the last sweep start.</p><table><thead><tr><th>Status (hex)</th><th>Decimal</th><th>Records</th></tr></thead><tbody>{rows}</tbody></table>{masks}<p>For records with a digital channel, sweep-start offsets span {low:.8g}–{high:.8g} s. Metadata on absent-channel records are retained in the inventory but excluded from count-reference training. A mask of <code>0xFFFFFFFF</code> has all 32 bits set; its detector mapping still requires the encoding definition. The rare status <code>0x8181C4BF</code> differs from <code>0x818144BF</code> by bit 15 (zero-based), with no mode interpretation inferred.</p><p>The scan-reference model conditions on exact status when sufficient other-day training records exist. Named modes and per-sample energy/angle sequences require the SWEAP-to-FIELDS interface definition or documented, time-matched SPAN-e housekeeping. <a href="sweap_metadata.json">Attributes and value inventory</a>.</p></section>'''
 values={'__N__':f'{n:,}','__FILES__':str(len(inventory)),'__K__':str(model['k']),'__R2__':f"{phase['cross_day_log1p_total_R2']:.3f}",'__FALLBACK__':str(phase['baseline_cross_status_fallback_n']),'__ENCOUNTERSECTION__':encsection,'__COVERAGESECTION__':covsection,'__SWEAPSECTION__':sweap}
 text=(Path(__file__).parent/'methods_template.html').read_text()
 for key,value in values.items():text=text.replace(key,value)
 (out/'methods.html').write_text(text)
if __name__=='__main__':build_methods(Path(__file__).parent)
